version: "3"

volumes:
  qiaqia-db:


services:
  database:
    image: postgres:14.2
    volumes:
      - qiaqia-db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=hi_postgresql
      - POSTGRES_PASSWORD=hellothisispassword
      - POSTGRES_DB=course-system
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis

  back-end:
    build: ./src/back-end-go/
    volumes:
      - ./server-go/config.yml:/usr/src/app/config.yml
      - ./scripts/wait-for-it.sh:/usr/src/app/wait-for-it.sh:ro
    depends_on:
      - database
      - redis
    environment:
      - GIN_MODE=release
    command: [ "./wait-for-it.sh", "database:5432", "--", "app" ]

  front-end:
    build: ./src/front-end/
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - back-end
    ports:
      - 80:80
